apiVersion: v1
kind: Pod
metadata:
  name: prometheus-sim
  namespace: monitoring
  labels:
    app: prometheus
    role: monitoring
spec:
  containers:
    - name: monitor
      image: nginx:alpine
      command: ["sleep", "3600"]
