apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-db-credentials-only
  namespace: secrets-lab
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["db-credentials"]
    verbs: ["get"]
