apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: kuzO3SfqA94MJrKtjLFM6AX4UoVlsTr86EnFSeJvxjk=
      - identity: {}
