apiVersion: v1
kind: Namespace
metadata:
  name: insecure-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: insecure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            runAsUser: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: insecure-app
automountServiceAccountToken: true
