apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: psa-baseline
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "4"
    limits.memory: "2Gi"
    pods: "10"
    secrets: "10"
    configmaps: "10"
