apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-app-label
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - policy-lab
      validate:
        message: "The label 'app' is required on all pods."
        pattern:
          metadata:
            labels:
              app: "?*"
    - name: require-team-label
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - policy-lab
      validate:
        message: "The label 'team' is required on all pods."
        pattern:
          metadata:
            labels:
              team: "?*"
