apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: falco-lab
  labels:
    app: test-app
spec:
  containers:
    - name: app
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
